### ISSUE TITLE
Splitting CSS Files

### ISSUE THREAD

**Issue by KDCinfo** [tonygambone/gulp-htmlsplit#1]
Hi there, 

I'm going to be trying your plugin, but was curious about splitting CSS files. CSS doesn't allow HTML comments (at least, my sass processor wouldn't). I was wondering what I might change the delimiter to in the code for a CSS comment with: /\* split filename.css */

Currently it's set to:
`var regex = /\s*<!--\s*split\s+(\S+)\s*-->\s*/g;`

Perhaps:
`var regex = /\s*/\*\s*split\s+(\S+)\s*\*/\s*/g;`

Swapped:
    `<!--` with `/\*`
    `-->` with `\*/`

Thanks.

**Comment by KDCinfo** [comment]
This did work. I just had to escape both the forward slash (/) and the asterisk (*).

`var regex = /\s*\/\*\s*split\s+(\S+)\s*\*\/\s*/g;`

**Thanks!!**

**Comment by tonygambone** [comment]
Sorry, didn't see this until now. Glad you worked it out, and thanks for following up with the results!

Thinking this would probably be good as a separate plugin for css files.
